#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmpleadosV1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdministracionEmpleados")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::GestionEmpleadosV1.Properties.Settings.Default.AdministracionEmpleadosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.existeEmpleado")]
		public int existeEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEmpleado", DbType="Int")] System.Nullable<int> iDEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_actualizarDatosGenerales")]
		public int proc_actualizarDatosGenerales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEmpleado", DbType="Int")] System.Nullable<int> iDEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(255)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(255)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nacionalidad", DbType="VarChar(255)")] string nacionalidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelEducativo", DbType="VarChar(255)")] string nivelEducativo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="VarChar(255)")] string fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(255)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(255)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(255)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Genero", DbType="VarChar(255)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoCivil", DbType="VarChar(255)")] string estadoCivil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesion", DbType="VarChar(255)")] string profesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFC", DbType="VarChar(255)")] string rFC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nota", DbType="VarChar(255)")] string nota)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEmpleado, nombre, apellido, nacionalidad, nivelEducativo, fechaNacimiento, celular, telefono, correo, genero, estadoCivil, profesion, direccion, rFC, nota);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_actualizarDatosHorarios")]
		public int proc_actualizarDatosHorarios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEmpleado", DbType="Int")] System.Nullable<int> iDEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dias", DbType="VarChar(255)")] string dias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InicioJornada", DbType="VarChar(255)")] string inicioJornada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinJornada", DbType="VarChar(255)")] string finJornada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEmpleado, dias, inicioJornada, finJornada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_actualizarDatosLaborales")]
		public int proc_actualizarDatosLaborales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEmpleado", DbType="Int")] System.Nullable<int> iDEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaIngreso", DbType="VarChar(255)")] string fechaIngreso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaRetiro", DbType="VarChar(255)")] string fechaRetiro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormaPago", DbType="VarChar(255)")] string formaPago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Area", DbType="VarChar(255)")] string area, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Salario", DbType="Int")] System.Nullable<int> salario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoTrabajador", DbType="VarChar(255)")] string estadoTrabajador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Turno", DbType="VarChar(255)")] string turno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cargo", DbType="VarChar(255)")] string cargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEmpleado, fechaIngreso, fechaRetiro, formaPago, area, salario, estadoTrabajador, turno, cargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_consultarDatos")]
		public ISingleResult<proc_consultarDatosResult> proc_consultarDatos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_consultarDatosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_consultarDatosDesc")]
		public ISingleResult<proc_consultarDatosDescResult> proc_consultarDatosDesc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_consultarDatosDescResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_eliminarEmpleado")]
		public int proc_eliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEmpleado", DbType="Int")] System.Nullable<int> iDEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_eliminarTodosEmpleados")]
		public int proc_eliminarTodosEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_insertarNuevoEmpleado")]
		public int proc_insertarNuevoEmpleado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEmpleado;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Nacionalidad;
		
		private string _NivelEducativo;
		
		private string _FechaNacimiento;
		
		private string _Celular;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Genero;
		
		private string _EstadoCivil;
		
		private string _Profesion;
		
		private string _Direccion;
		
		private string _RFC;
		
		private string _FechaIngreso;
		
		private string _FechaRetiro;
		
		private string _FormaPago;
		
		private string _Area;
		
		private System.Nullable<int> _Salario;
		
		private string _EstadoTrabajador;
		
		private string _Turno;
		
		private string _Cargo;
		
		private string _Dias;
		
		private string _InicioJornada;
		
		private string _FinJornada;
		
		private string _Nota;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEmpleadoChanging(int value);
    partial void OnIDEmpleadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNacionalidadChanging(string value);
    partial void OnNacionalidadChanged();
    partial void OnNivelEducativoChanging(string value);
    partial void OnNivelEducativoChanged();
    partial void OnFechaNacimientoChanging(string value);
    partial void OnFechaNacimientoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    partial void OnEstadoCivilChanging(string value);
    partial void OnEstadoCivilChanged();
    partial void OnProfesionChanging(string value);
    partial void OnProfesionChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnRFCChanging(string value);
    partial void OnRFCChanged();
    partial void OnFechaIngresoChanging(string value);
    partial void OnFechaIngresoChanged();
    partial void OnFechaRetiroChanging(string value);
    partial void OnFechaRetiroChanged();
    partial void OnFormaPagoChanging(string value);
    partial void OnFormaPagoChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnSalarioChanging(System.Nullable<int> value);
    partial void OnSalarioChanged();
    partial void OnEstadoTrabajadorChanging(string value);
    partial void OnEstadoTrabajadorChanged();
    partial void OnTurnoChanging(string value);
    partial void OnTurnoChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnDiasChanging(string value);
    partial void OnDiasChanged();
    partial void OnInicioJornadaChanging(string value);
    partial void OnInicioJornadaChanged();
    partial void OnFinJornadaChanging(string value);
    partial void OnFinJornadaChanged();
    partial void OnNotaChanging(string value);
    partial void OnNotaChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDEmpleado
		{
			get
			{
				return this._IDEmpleado;
			}
			set
			{
				if ((this._IDEmpleado != value))
				{
					this.OnIDEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IDEmpleado = value;
					this.SendPropertyChanged("IDEmpleado");
					this.OnIDEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(255)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="VarChar(255)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this.OnNacionalidadChanging(value);
					this.SendPropertyChanging();
					this._Nacionalidad = value;
					this.SendPropertyChanged("Nacionalidad");
					this.OnNacionalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelEducativo", DbType="VarChar(255)")]
		public string NivelEducativo
		{
			get
			{
				return this._NivelEducativo;
			}
			set
			{
				if ((this._NivelEducativo != value))
				{
					this.OnNivelEducativoChanging(value);
					this.SendPropertyChanging();
					this._NivelEducativo = value;
					this.SendPropertyChanged("NivelEducativo");
					this.OnNivelEducativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="VarChar(255)")]
		public string FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(255)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(255)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(255)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(255)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivil", DbType="VarChar(255)")]
		public string EstadoCivil
		{
			get
			{
				return this._EstadoCivil;
			}
			set
			{
				if ((this._EstadoCivil != value))
				{
					this.OnEstadoCivilChanging(value);
					this.SendPropertyChanging();
					this._EstadoCivil = value;
					this.SendPropertyChanged("EstadoCivil");
					this.OnEstadoCivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(255)")]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this.OnProfesionChanging(value);
					this.SendPropertyChanging();
					this._Profesion = value;
					this.SendPropertyChanged("Profesion");
					this.OnProfesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(255)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this.OnRFCChanging(value);
					this.SendPropertyChanging();
					this._RFC = value;
					this.SendPropertyChanged("RFC");
					this.OnRFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso", DbType="VarChar(255)")]
		public string FechaIngreso
		{
			get
			{
				return this._FechaIngreso;
			}
			set
			{
				if ((this._FechaIngreso != value))
				{
					this.OnFechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._FechaIngreso = value;
					this.SendPropertyChanged("FechaIngreso");
					this.OnFechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRetiro", DbType="VarChar(255)")]
		public string FechaRetiro
		{
			get
			{
				return this._FechaRetiro;
			}
			set
			{
				if ((this._FechaRetiro != value))
				{
					this.OnFechaRetiroChanging(value);
					this.SendPropertyChanging();
					this._FechaRetiro = value;
					this.SendPropertyChanged("FechaRetiro");
					this.OnFechaRetiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaPago", DbType="VarChar(255)")]
		public string FormaPago
		{
			get
			{
				return this._FormaPago;
			}
			set
			{
				if ((this._FormaPago != value))
				{
					this.OnFormaPagoChanging(value);
					this.SendPropertyChanging();
					this._FormaPago = value;
					this.SendPropertyChanged("FormaPago");
					this.OnFormaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(255)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Int")]
		public System.Nullable<int> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this.OnSalarioChanging(value);
					this.SendPropertyChanging();
					this._Salario = value;
					this.SendPropertyChanged("Salario");
					this.OnSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoTrabajador", DbType="VarChar(255)")]
		public string EstadoTrabajador
		{
			get
			{
				return this._EstadoTrabajador;
			}
			set
			{
				if ((this._EstadoTrabajador != value))
				{
					this.OnEstadoTrabajadorChanging(value);
					this.SendPropertyChanging();
					this._EstadoTrabajador = value;
					this.SendPropertyChanged("EstadoTrabajador");
					this.OnEstadoTrabajadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="VarChar(255)")]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this.OnTurnoChanging(value);
					this.SendPropertyChanging();
					this._Turno = value;
					this.SendPropertyChanged("Turno");
					this.OnTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(255)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(255)")]
		public string Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				if ((this._Dias != value))
				{
					this.OnDiasChanging(value);
					this.SendPropertyChanging();
					this._Dias = value;
					this.SendPropertyChanged("Dias");
					this.OnDiasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InicioJornada", DbType="VarChar(255)")]
		public string InicioJornada
		{
			get
			{
				return this._InicioJornada;
			}
			set
			{
				if ((this._InicioJornada != value))
				{
					this.OnInicioJornadaChanging(value);
					this.SendPropertyChanging();
					this._InicioJornada = value;
					this.SendPropertyChanged("InicioJornada");
					this.OnInicioJornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinJornada", DbType="VarChar(255)")]
		public string FinJornada
		{
			get
			{
				return this._FinJornada;
			}
			set
			{
				if ((this._FinJornada != value))
				{
					this.OnFinJornadaChanging(value);
					this.SendPropertyChanging();
					this._FinJornada = value;
					this.SendPropertyChanged("FinJornada");
					this.OnFinJornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="VarChar(255)")]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class proc_consultarDatosResult
	{
		
		private int _IDEmpleado;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Nacionalidad;
		
		private string _NivelEducativo;
		
		private string _FechaNacimiento;
		
		private string _Celular;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Genero;
		
		private string _EstadoCivil;
		
		private string _Profesion;
		
		private string _Direccion;
		
		private string _RFC;
		
		private string _FechaIngreso;
		
		private string _FechaRetiro;
		
		private string _FormaPago;
		
		private string _Area;
		
		private System.Nullable<int> _Salario;
		
		private string _EstadoTrabajador;
		
		private string _Turno;
		
		private string _Cargo;
		
		private string _Dias;
		
		private string _InicioJornada;
		
		private string _FinJornada;
		
		private string _Nota;
		
		public proc_consultarDatosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEmpleado", DbType="Int NOT NULL")]
		public int IDEmpleado
		{
			get
			{
				return this._IDEmpleado;
			}
			set
			{
				if ((this._IDEmpleado != value))
				{
					this._IDEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(255)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="VarChar(255)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this._Nacionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelEducativo", DbType="VarChar(255)")]
		public string NivelEducativo
		{
			get
			{
				return this._NivelEducativo;
			}
			set
			{
				if ((this._NivelEducativo != value))
				{
					this._NivelEducativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="VarChar(255)")]
		public string FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(255)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(255)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(255)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(255)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this._Genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivil", DbType="VarChar(255)")]
		public string EstadoCivil
		{
			get
			{
				return this._EstadoCivil;
			}
			set
			{
				if ((this._EstadoCivil != value))
				{
					this._EstadoCivil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(255)")]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(255)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this._RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso", DbType="VarChar(255)")]
		public string FechaIngreso
		{
			get
			{
				return this._FechaIngreso;
			}
			set
			{
				if ((this._FechaIngreso != value))
				{
					this._FechaIngreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRetiro", DbType="VarChar(255)")]
		public string FechaRetiro
		{
			get
			{
				return this._FechaRetiro;
			}
			set
			{
				if ((this._FechaRetiro != value))
				{
					this._FechaRetiro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaPago", DbType="VarChar(255)")]
		public string FormaPago
		{
			get
			{
				return this._FormaPago;
			}
			set
			{
				if ((this._FormaPago != value))
				{
					this._FormaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(255)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Int")]
		public System.Nullable<int> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this._Salario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoTrabajador", DbType="VarChar(255)")]
		public string EstadoTrabajador
		{
			get
			{
				return this._EstadoTrabajador;
			}
			set
			{
				if ((this._EstadoTrabajador != value))
				{
					this._EstadoTrabajador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="VarChar(255)")]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this._Turno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(255)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(255)")]
		public string Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				if ((this._Dias != value))
				{
					this._Dias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InicioJornada", DbType="VarChar(255)")]
		public string InicioJornada
		{
			get
			{
				return this._InicioJornada;
			}
			set
			{
				if ((this._InicioJornada != value))
				{
					this._InicioJornada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinJornada", DbType="VarChar(255)")]
		public string FinJornada
		{
			get
			{
				return this._FinJornada;
			}
			set
			{
				if ((this._FinJornada != value))
				{
					this._FinJornada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="VarChar(255)")]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this._Nota = value;
				}
			}
		}
	}
	
	public partial class proc_consultarDatosDescResult
	{
		
		private int _IDEmpleado;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Nacionalidad;
		
		private string _NivelEducativo;
		
		private string _FechaNacimiento;
		
		private string _Celular;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Genero;
		
		private string _EstadoCivil;
		
		private string _Profesion;
		
		private string _Direccion;
		
		private string _RFC;
		
		private string _FechaIngreso;
		
		private string _FechaRetiro;
		
		private string _FormaPago;
		
		private string _Area;
		
		private System.Nullable<int> _Salario;
		
		private string _EstadoTrabajador;
		
		private string _Turno;
		
		private string _Cargo;
		
		private string _Dias;
		
		private string _InicioJornada;
		
		private string _FinJornada;
		
		private string _Nota;
		
		public proc_consultarDatosDescResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEmpleado", DbType="Int NOT NULL")]
		public int IDEmpleado
		{
			get
			{
				return this._IDEmpleado;
			}
			set
			{
				if ((this._IDEmpleado != value))
				{
					this._IDEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(255)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="VarChar(255)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this._Nacionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelEducativo", DbType="VarChar(255)")]
		public string NivelEducativo
		{
			get
			{
				return this._NivelEducativo;
			}
			set
			{
				if ((this._NivelEducativo != value))
				{
					this._NivelEducativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="VarChar(255)")]
		public string FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(255)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(255)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(255)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(255)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this._Genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivil", DbType="VarChar(255)")]
		public string EstadoCivil
		{
			get
			{
				return this._EstadoCivil;
			}
			set
			{
				if ((this._EstadoCivil != value))
				{
					this._EstadoCivil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(255)")]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(255)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this._RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso", DbType="VarChar(255)")]
		public string FechaIngreso
		{
			get
			{
				return this._FechaIngreso;
			}
			set
			{
				if ((this._FechaIngreso != value))
				{
					this._FechaIngreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRetiro", DbType="VarChar(255)")]
		public string FechaRetiro
		{
			get
			{
				return this._FechaRetiro;
			}
			set
			{
				if ((this._FechaRetiro != value))
				{
					this._FechaRetiro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaPago", DbType="VarChar(255)")]
		public string FormaPago
		{
			get
			{
				return this._FormaPago;
			}
			set
			{
				if ((this._FormaPago != value))
				{
					this._FormaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(255)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Int")]
		public System.Nullable<int> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this._Salario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoTrabajador", DbType="VarChar(255)")]
		public string EstadoTrabajador
		{
			get
			{
				return this._EstadoTrabajador;
			}
			set
			{
				if ((this._EstadoTrabajador != value))
				{
					this._EstadoTrabajador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="VarChar(255)")]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this._Turno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(255)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(255)")]
		public string Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				if ((this._Dias != value))
				{
					this._Dias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InicioJornada", DbType="VarChar(255)")]
		public string InicioJornada
		{
			get
			{
				return this._InicioJornada;
			}
			set
			{
				if ((this._InicioJornada != value))
				{
					this._InicioJornada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinJornada", DbType="VarChar(255)")]
		public string FinJornada
		{
			get
			{
				return this._FinJornada;
			}
			set
			{
				if ((this._FinJornada != value))
				{
					this._FinJornada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="VarChar(255)")]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this._Nota = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
